#!/usr/bin/env node
// Generates apps-script/Zones.js: IANA time zone -> country name (pt-BR).
//
//   node tools/gen_zones.js
//
// The short-link stub sends the visitor's time zone
// (Intl.DateTimeFormat().resolvedOptions().timeZone, e.g. "America/Sao_Paulo")
// and the counter turns it into an ESTIMATED country with this table: no IP,
// no third-party lookup. A zone says where the device's clock is set, which is
// almost always the country the person is in — "almost": a traveller who never
// changed the clock counts as home.
//
// Sources, both from the tzdata package of the machine that runs this:
//   /usr/share/zoneinfo/zone.tab   one canonical zone per line, with its country
//   /usr/share/zoneinfo/tzdata.zi  "L <target> <alias>" link lines — browsers
//                                  still report some old names (Asia/Calcutta)
// Country names come from Node's ICU (Intl.DisplayNames, pt-BR), so the sheet
// reads "Brasil", not "BR" or "Brazil".
'use strict';
const fs = require('fs');
const path = require('path');

const ZONEINFO = '/usr/share/zoneinfo';
const names = new Intl.DisplayNames(['pt-BR'], { type: 'region' });

const country = {};
for (const line of fs.readFileSync(path.join(ZONEINFO, 'zone.tab'), 'utf8').split('\n')) {
  if (!line || line[0] === '#') continue;
  const [cc, , zone] = line.split('\t');
  country[zone] = names.of(cc);
}
let links = 0;
for (const line of fs.readFileSync(path.join(ZONEINFO, 'tzdata.zi'), 'utf8').split('\n')) {
  const m = line.match(/^L (\S+) (\S+)$/);
  if (m && country[m[1]] && !country[m[2]]) { country[m[2]] = country[m[1]]; links++; }
}

const zones = Object.keys(country).sort();
if (zones.length < 300 || country['America/Sao_Paulo'] !== 'Brasil') {
  throw new Error(`implausible table: ${zones.length} zones, Sao_Paulo=${country['America/Sao_Paulo']}`);
}
const out = [
  '// GENERATED by tools/gen_zones.js — do not edit by hand; rerun the generator.',
  '// IANA time zone -> country (pt-BR), from tzdata zone.tab + its link aliases.',
  '// The counter uses it to ESTIMATE the visitor\'s country from the time zone',
  '// the stub sends; nothing else about the visitor is involved.',
  'var ZONE_COUNTRY = {',
  zones.map((z) => `  ${JSON.stringify(z)}: ${JSON.stringify(country[z])}`).join(',\n'),
  '};',
  '',
].join('\n');
fs.writeFileSync(path.join(__dirname, '..', 'apps-script', 'Zones.js'), out);
console.log(`apps-script/Zones.js: ${zones.length} zones (${links} of them link aliases)`);
